services:
  telegram-bot:
    build: .
    container_name: best_places_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: best_places_redis
    restart: always
