# ... (начало файла)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          set -e  # <-- ДОБАВИТЬ ЭТУ СТРОКУ!

          cd /home/deployer/best-places-bot
          git pull origin main
          
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
          
          docker-compose up --build -d
          docker image prune -f
